### PR TITLE
Multitenancy: update docs and build

### PR DESCRIPTION
**Pull request by bzz**
First step of catch up with the latest feedback.  This PR should make fresh clean build simpler.

Test plan:
- `git clone git@github.com:NFLabs/z-manager.git ; cd z-manager`
- `git checkout build-update`
- `cd multitenancy`
- `./build-all.sh`

\cc @khalidhuseynov @felizbear for a review

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
looks good

**Comment by minahlee** [comment]
LGTM

**Comment by bzz** [comment]
Thank you for timely reviews!

**Comment by khalidhuseynov** [comment]
tested and looks good, thanks for adding more info!

**Pull request merged**
